language: android
android:
  components:
    # build tools version
    - build-tools-22.0.1
    
    # android apk version
    - android-19
    
    #other
    - extra
    - addon
    
    # system images
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
