language: android
android:
  components:
    # build tools version
    - build-tools-22.0.1
    
    # android apk version
    - android-19
    
    #other
    - extra
    - addon
    
    # system images
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
    
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest --stacktrace
